import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="max-w-7xl md:px-8 sm:px-4 px-3 mx-auto h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
